server:
  port: 1114
spring:
  application:
    name: hello-service
eureka:
  client:
    serviceUrl:
      defaultZone: @eureka.client.serviceUrl.defaultZone@
  instance:
    preferIpAddress: true
    hostname: hello-service