server:
  port: 1115
spring:
  application:
    name: ribbon-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: @eureka.client.serviceUrl.defaultZone@
  instance:
    preferIpAddress: true
    hostname: ribbon-consumer